# Site settings
title: Annabel Lee
description: |
  Annabel Lee is your best and only friend. She spends every waking moment either building something or occassionally dancing.

url: http://annabel-lee.xyz

about_title: About
projects_title: Home

# User settings
user_description_appendix: |
  I stole this site to write about my interests: hardware and dance.

  Rassaby built this site in [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so since I liked it,
  I forked it on [GitHub][github] and made my own version.

  [github]: https://github.com/halfsohappy/
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: cyberannabel@gmail.com
#linkedin: lrassaby
github: halfsohappy
#angellist: rassaby

relevant_tags: ['projects', 'music', 'tech-blog']

resume_url: https://docs.google.com/document/d/1dJIboSF-ktdaP28DDu-gcuOW1SCCnkSdqtodJGwYkaA/export?format=pdf
music_resume_url: https://docs.google.com/document/d/17F3g8jx2UHby77P7shJlsKAW2Efasuc1HuQ3Ro3v3zI/export?format=pdf

author: Annabel Lee
author_title: Electrical/Computer Engineer
author_photo: profile-photo.jpg
user_description_short: |
  I lovea da women.
  
  I've founded a [couple][wirefreight] of [things][ppp]. Previously, I led the new products team engineering team at
  Phosphorus Genomics, analyzing genetic data and educating tens of thousands of people on their risks of developing or
  passing on genetic diseases.

  Away from the keyboard, I make food and music. I'm half of a band called [Cellolele][cellolele] and I once played in
  an ad for [Versace][versace].

  [scala]: https://www.scala-lang.org/
  [couple]: https://wirefreight.com/
  [cellolele]: /cellolele-toxic/
  [wirefreight]: http://wirefreight.com/
  [ppp]: http://postpartumproject.com/
  [versace]: /versace-eyewear


## Disqus
#disqus_identifier: rassaby

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,louis rassaby,rassaby'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'

sass:
    sass_dir: _sass


plugins:
  - jekyll-feed


include: [_sass, _pages]

exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'README.md']
